export const lightTheme = {
    body: '#FFF',
    text: '#451f7a',
    toggleButtonText: '#666',
    toggleButton: '#451f7a',
    lightText: '#FFF',
    lightTextWeight: 'normal',
    cardColor: '#FFF',
    grayH2: '#333333',
    grayText: 'gray',
    teamBg: 'f2f2fe',
    cardSocialA: '#8797a1',
    navBackground: '#FFF',
    formBackground: '#f3f2f8',
}
export const darkTheme = {
    body: '#451f7a',
    text: '#FAFAFA',
    buttonToggleText: '#451f7a',
    buttonToggleBg: '#CCC',
    lightText: '#000',
    lightTextWeight: 'bolder',
    cardColor: '#5a2f96',
    grayText: '#EFEFEF',
    grayH2: '#FFF',
    teamBg: '#333333',
    cardSocialA: 'lightgray',
    navBackground: '#CCC',
    formBackground: '#CCC',
}
